# Dimension

## Matrix multiplication

In [1]:
import numpy as np
# matrix multiplication
a = np.array([[1, 0], 
              [0, 1]])
b = np.array([[4, 1], 
              [2, 2]])
print('a * b = \n', np.dot(a, b))
print('a @ b = \n', a @ b)
c = a / b
print('c = \n', c)

a * b = 
 [[4 1]
 [2 2]]
a @ b = 
 [[4 1]
 [2 2]]
c = 
 [[0.25 0.  ]
 [0.   0.5 ]]


## Dot product

ใช้ฟังก์ชัน `numpy.dot` (https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [2]:
# dot product
d = np.array([1, 2, 3])
e = np.array([4, 1, 2])
print('d . e = ', np.dot(d, e))
print('d . e = ', d @ e)

d . e =  12
d . e =  12


## Norms

ใช้ฟังก์ชัน `numpy.linalg.norm` (https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

In [3]:
# norm
f = np.array([4, 3])
print('p=2, |f| = ', np.linalg.norm(f))
print('p=1, |f| = ', np.linalg.norm(f, ord=1))
print('p=inf, |f| = ', np.linalg.norm(f, ord=np.inf))
print('p=2, |b| = ', np.linalg.norm(b, axis=1))

p=2, |f| =  5.0
p=1, |f| =  7.0
p=inf, |f| =  4.0
p=2, |b| =  [4.12310563 2.82842712]


In [4]:
b

array([[4, 1],
       [2, 2]])

In [5]:
17**0.5

4.123105625617661

In [6]:
8**0.5

2.8284271247461903

## Unit vector

In [7]:
# unit vector
d_hat = d / (d**2).sum()**0.5
print(d_hat, ', norm of d_hat = ', np.linalg.norm(d_hat))

[0.26726124 0.53452248 0.80178373] , norm of d_hat =  1.0


In [8]:
d/np.linalg.norm(d)

array([0.26726124, 0.53452248, 0.80178373])

## Distance

ใช้ฟังก์ชัน `scipy.spatial.distance.euclidean` (https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.spatial.distance.euclidean.html)

In [9]:
d

array([1, 2, 3])

In [10]:
e

array([4, 1, 2])

In [11]:
np.linalg.norm(d-e)

3.3166247903554

In [12]:
# distance
from scipy.spatial import distance
dst = distance.euclidean(d, e)
print('|d - e| = ', dst)

|d - e| =  3.3166247903554


## Rank

ใช้ฟังก์ชัน `numpy.linalg.matrix_rank` (https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html)

In [13]:
# rank
from numpy.linalg import matrix_rank
rankA = matrix_rank(np.array([[2, 5, -3, -4, 8], 
                              [4, 7, -4, -3, 9], 
                              [6, 9, -5, 2, 4], 
                              [0, -9, 6, 5, -6]]))
print('rank A = ', rankA)

rank A =  3


## Cross product

ใช้ฟังก์ชัน `numpy.cross` (https://numpy.org/doc/stable/reference/generated/numpy.cross.html)

In [14]:
# cross product
g = [1, 2, 3]
h = [4, 5, 6]
# print('g x h = ', np.cross(g, h))
# print('h x g = ', np.cross(h, g))
gxh_abs = np.linalg.norm(np.cross(g, h))
g_abs = np.linalg.norm(g)
h_abs = np.linalg.norm(h)
theta1 = np.arcsin(gxh_abs / (g_abs * h_abs))
print('theta = sin-1(|g x h| / |g||h|) = ', theta1)

gdh_abs = np.dot(g, h)
theta2 = np.arccos(gdh_abs / (g_abs * h_abs))
print('theta = cos-1(|g . h| / |g||h|) = ', theta2)

theta = sin-1(|g x h| / |g||h|) =  0.22572612855273394
theta = cos-1(|g . h| / |g||h|) =  0.2257261285527342
