# Eigenvalues and Eigenvectors

ใช้ฟังก์ชัน `numpy.linalg.eig` (https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)

In [1]:
import numpy as np
from numpy import linalg as LA

# eigenvalues and eigenvectors
A = np.array([[4, 2, 2],
              [-1, 1, -1],
              [6, 6, 8]])
w, v = LA.eig(A)
print(A)
for i in range(w.size):
    print(f'Eigenvalue {i} = {w[i]:.2f}, eigenvector = {v[:,i]}')

[[ 4  2  2]
 [-1  1 -1]
 [ 6  6  8]]
Eigenvalue 0 = 9.00, eigenvector = [-0.31234752  0.15617376 -0.93704257]
Eigenvalue 1 = 2.00, eigenvector = [-0.63500064 -0.12700013  0.76200076]
Eigenvalue 2 = 2.00, eigenvector = [-0.41580471  0.81644967 -0.40064496]


## Trace 

$tr(A) = \sum_i A_{i,i}$

https://en.wikipedia.org/wiki/Trace_(linear_algebra)

In [2]:
np.trace(A)

13

In [3]:
np.round(w.sum(),2)

13.0

## Determinant and Eigenvalues

The product of all eigenvalues of $A$ is the same as the determinant of $A$.

In [4]:
LA.det(A)

36.0

In [5]:
np.round(np.prod(w), 2)

36.0

## Eigenvalues of Triangular matrix

Eigenvalues of triangular matrix are the diagonal entries.

In [6]:
A = np.array([[3, 6, -8], 
              [0, 0, 6], 
              [0, 0, 2]])
w, v = LA.eig(A)
print(A)
for i in range(w.size):
    print(f'Eigenvalue {i} = {w[i]}, eigenvector = {v[:,i]}')

[[ 3  6 -8]
 [ 0  0  6]
 [ 0  0  2]]
Eigenvalue 0 = 3.0, eigenvector = [1. 0. 0.]
Eigenvalue 1 = 0.0, eigenvector = [-0.89442719  0.4472136   0.        ]
Eigenvalue 2 = 2.0, eigenvector = [-0.95346259  0.28603878  0.09534626]


In [7]:
B = np.array([[4, 0, 0], 
              [-2, 1, 0], 
              [5, 3, 4]])
w, v = LA.eig(B)
print(B)
for i in range(w.size):
    print(f'Eigenvalue {i} = {w[i]}, eigenvector = {v[:,i]}')

[[ 4  0  0]
 [-2  1  0]
 [ 5  3  4]]
Eigenvalue 0 = 4.0, eigenvector = [0. 0. 1.]
Eigenvalue 1 = 1.0, eigenvector = [ 0.          0.70710678 -0.70710678]
Eigenvalue 2 = 4.0, eigenvector = [ 2.96059473e-16 -1.97372982e-16 -1.00000000e+00]


## The Characteristic Equation

$$\det(A - \lambda I) = 0$$

In [8]:
# det(A- lambda I) = 0
print('det(B - \u03BB I) = ', np.linalg.det(B - w[0]*np.eye(3)))

det(B - λ I) =  0.0


## Diagonalization

The eigenvalue–eigenvector can be displayed in a factorization of the form  $A = P D P^{-1}$  where $D$ is a diagonal matrix.

In [9]:
# diagnoalize
A = np.array([[1, 3, 3], [-3, -5, -3], [3, 3, 1]])
w, v = LA.eig(A)
print(A)
for i in range(w.size):
    print(f'Eigenvalue {i} = {w[i]}, eigenvector = {v[:,i]}')

print('AP = \n', A @ v)
print('PD = \n', v @ np.diag(w))

print('A = \n', A)
print('PDP-1 = \n',  v @ np.diag(w) @ LA.inv(v))

[[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]
Eigenvalue 0 = 1.0000000000000004, eigenvector = [ 0.57735027 -0.57735027  0.57735027]
Eigenvalue 1 = -2.0, eigenvector = [-6.40987562e-17 -7.07106781e-01  7.07106781e-01]
Eigenvalue 2 = -1.9999999999999996, eigenvector = [-0.71108247  0.70306288  0.00801959]
AP = 
 [[ 5.77350269e-01  8.88178420e-16  1.42216494e+00]
 [-5.77350269e-01  1.41421356e+00 -1.40612575e+00]
 [ 5.77350269e-01 -1.41421356e+00 -1.60391817e-02]]
PD = 
 [[ 5.77350269e-01  1.28197512e-16  1.42216494e+00]
 [-5.77350269e-01  1.41421356e+00 -1.40612575e+00]
 [ 5.77350269e-01 -1.41421356e+00 -1.60391817e-02]]
A = 
 [[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]
PDP-1 = 
 [[ 1.  3.  3.]
 [-3. -5. -3.]
 [ 3.  3.  1.]]


## Symmetric matrix

Key properties of symmetric matrix:
1. A symmetric matrix has only real eigenvalues.
2. The eigenvectors can be chosen orthonormal.


In [10]:
# symmetric matrix
D = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
w, v = LA.eig(D)
print('D = \n', D)
for i in range(w.size):
    print(f'Eigenvalue {i} = {w[i]:.2f}, eigenvector = {v[:,i]}')

print('Q-1 = \n', LA.inv(v))
print('QT  = \n', v.T)

D = 
 [[1 2 3]
 [2 3 4]
 [3 4 5]]
Eigenvalue 0 = 9.62, eigenvector = [-0.38508979 -0.55951021 -0.73393063]
Eigenvalue 1 = -0.62, eigenvector = [-0.82767094 -0.14241368  0.54284358]
Eigenvalue 2 = 0.00, eigenvector = [ 0.40824829 -0.81649658  0.40824829]
Q-1 = 
 [[-0.38508979 -0.55951021 -0.73393063]
 [-0.82767094 -0.14241368  0.54284358]
 [ 0.40824829 -0.81649658  0.40824829]]
QT  = 
 [[-0.38508979 -0.55951021 -0.73393063]
 [-0.82767094 -0.14241368  0.54284358]
 [ 0.40824829 -0.81649658  0.40824829]]
