# Determinant

* 10 Properties of Determinants
* Determinant Computation

In [1]:
import numpy as np
import scipy.linalg
np.set_printoptions(precision=2)

## 10 Properties of Determinants

1. The determinant of the nxn identity matrix is 1

In [2]:
I = np.eye(3)
scipy.linalg.det(I)

1.0

2. The determinant changes sign when two rows are exchanged

In [3]:
a = np.array([[1, 2], 
              [3, 4]])
scipy.linalg.det(a)

-2.0

In [4]:
b = a[[1,0]]
scipy.linalg.det(b)

2.0

3. The determinant is a linear function of each row separately

In [5]:
a = np.array([[1, 2], 
              [3, 4]])
scipy.linalg.det(a)

-2.0

In [6]:
b = a.copy()
b[0] = b[0] * 3
scipy.linalg.det(b)

-6.0

In [7]:
b = a.copy()
b[1] = b[1] + 5
scipy.linalg.det(b)

-7.0

4. If two rows of $A$ are equal, then $\det A = 0$.

In [8]:
a = np.array([[1, 2], 
              [1, 2]])
scipy.linalg.det(a)

0.0

5. Subtracting a multiple of one row from another row leaves $\det A$ unchanged.

In [9]:
a = np.array([[1, 2], 
              [3, 4]])
print('A = \n', a)
print('det A = \n', scipy.linalg.det(a))

A = 
 [[1 2]
 [3 4]]
det A = 
 -2.0


In [10]:
a[1] = a[1] - 2*a[0]
print('A = \n', a)
print('det A = \n', scipy.linalg.det(a))

A = 
 [[1 2]
 [1 0]]
det A = 
 -2.0


6. A matrix with a row of zeros has $\det A = 0$.

In [11]:
a = np.array([[1, 2], 
              [3, 4]])
a[0] = 0
print('A = \n', a)
print('det A = \n', scipy.linalg.det(a))

A = 
 [[0 0]
 [3 4]]
det A = 
 0.0


7. If $A$ is triangular then $\det A = a_{11}, a_{22}, \dots, a_{nn}$ = product of diagonal entries.


In [12]:
A = np.array([[2, 3, 2], 
              [1, 3, 2], 
              [3, 4, 1]])
P, L, U = scipy.linalg.lu(A)

In [13]:
print('A = \n', A)
print('det A = \n', scipy.linalg.det(A))

A = 
 [[2 3 2]
 [1 3 2]
 [3 4 1]]
det A = 
 -5.0


In [14]:
print('L = \n', L)
print('det L = \n', scipy.linalg.det(L))

L = 
 [[1.   0.   0.  ]
 [0.33 1.   0.  ]
 [0.67 0.2  1.  ]]
det L = 
 1.0


In [15]:
print('P = \n', P)
print('det P = \n', scipy.linalg.det(P))

P = 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
det P = 
 -1.0


In [16]:
print('U = \n', U)
print('det U = \n', scipy.linalg.det(U))

U = 
 [[3.   4.   1.  ]
 [0.   1.67 1.67]
 [0.   0.   1.  ]]
det U = 
 5.0


In [17]:
np.diag(U).prod() * np.linalg.det(P)

-5.0

8. If $A$ is singular then $\det A = 0$. If $A$ is invertible then $\det A \neq 0$.

In [18]:
a = np.array([[1, 2], 
              [3, 4]])
print(f'det(a) = {scipy.linalg.det(a)}')
print('A-1 = \n', scipy.linalg.inv(a))

det(a) = -2.0
A-1 = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
b = np.array([[1, 3], 
              [1, 3]])
print(f'det(b) = {scipy.linalg.det(b)}')
print('B-1 = \n', scipy.linalg.inv(b))

det(b) = 0.0


LinAlgError: singular matrix

9. The determinant of $AB$ is $\det A$ times $\det B$, $| AB | = | A | | B |$,

In [20]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[1, 0], 
              [1, 2]])
print(f'a = \n{a}')
print(f'b = \n{b}')
print(f'det(a) = {scipy.linalg.det(a)}')
print(f'det(b) = {scipy.linalg.det(b)}')
print(f'det(ab) = {scipy.linalg.det(np.matmul(a,b))}')
print(f'det(a)det(b) = {scipy.linalg.det(a) * scipy.linalg.det(b)}')

a = 
[[1 2]
 [3 4]]
b = 
[[1 0]
 [1 2]]
det(a) = -2.0
det(b) = 2.0
det(ab) = -4.0
det(a)det(b) = -4.0


10. The transpose $A^T$ has the same determinant as $A$.

In [21]:
a = np.array([[1, 2], 
              [3, 4]])
print('A = \n', a)
print('det A = \n', scipy.linalg.det(a))

A = 
 [[1 2]
 [3 4]]
det A = 
 -2.0


In [22]:
print('A^T = \n', a.T)
print('det A^T = \n', scipy.linalg.det(a.T))

A^T = 
 [[1 3]
 [2 4]]
det A^T = 
 -2.0


## Determinant Computation

In `SciPy`, the determinant is computed via LU factorization, LAPACK routine z/dgetrf.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.det.html

In [23]:
a = np.array([[1, 2, 3], 
              [3, 1, 2],
              [3, 2, 1]])
print(f'a = \n{a}')
print(f'det(a) = {scipy.linalg.det(a)}')

a = 
[[1 2 3]
 [3 1 2]
 [3 2 1]]
det(a) = 12.0


In [24]:
a = np.array([[1, 2, 3], 
              [3, 1, 2],
              [3, 2, 1]])
lu, piv = scipy.linalg.lu_factor(a)

In [25]:
lu

array([[ 3.  ,  1.  ,  2.  ],
       [ 0.33,  1.67,  2.33],
       [ 1.  ,  0.6 , -2.4 ]])

In [26]:
L, U = np.tril(lu, k=-1) + np.eye(3), np.triu(lu)

In [27]:
print(L)
print(U)

[[1.   0.   0.  ]
 [0.33 1.   0.  ]
 [1.   0.6  1.  ]]
[[ 3.    1.    2.  ]
 [ 0.    1.67  2.33]
 [ 0.    0.   -2.4 ]]


In [28]:
L@U

array([[3., 1., 2.],
       [1., 2., 3.],
       [3., 2., 1.]])

In [29]:
np.prod(np.diag(U))

-12.000000000000002

### Other tricks

$\det (2 I_n) = n^2$

In [30]:
print(f'det(2I) = {scipy.linalg.det(2*np.eye(16))}')

det(2I) = 65536.0
