# Matrix Factorization

* ฟังก์ชันที่ควรรู้สำหรับแมทริกซ์
* LU Decomposition โดยใช้ `SciPy`
* LU Decomposition โดยใช้ Doolittle Algorithm

## ฟังก์ชันที่ควรรู้สำหรับแมทริกซ์

`np.eye` สำหรับสร้าง identity matrix

In [1]:
import numpy as np
a = np.array([[0, 1, 2], 
              [1, 0, 3], 
              [4, -3, 8]])
b = np.eye(a.shape[0])

In [2]:
print(a.shape)

(3, 3)


In [3]:
print(a)

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]


ฟังก์ชัน `np.diag` สำหรับหา diagonal entry ของแมทริกซ์

In [4]:
print(np.diag(a))

[0 0 8]


In [5]:
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
c = np.array([[1],[2],[3]])
c.shape

(3, 1)

In [7]:
c

array([[1],
       [2],
       [3]])

`ndim` ใช้บอกจำนวนมิติของอาเรย์

In [8]:
c.ndim

2

In [9]:
np.diag(c)

array([1])

In [10]:
d = np.array([1,2,3])
d.shape

(3,)

In [11]:
d.ndim

1

ในขณะเดียวกันฟังก์ชัน `np.diag` สามารถใช้ในการสร้าง diagonal matrix ได้ด้วยโดยป้อน 1D array ให้

In [12]:
np.diag(d)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
d

array([1, 2, 3])

In [14]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## LU Decomposition โดยใช้ `SciPy`

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html

In [16]:
import pprint
import scipy.linalg

A = np.array([[2, 3, 2], 
              [1, 3, 2], 
              [3, 4, 1]])
P, L, U = scipy.linalg.lu(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

print("PLU :")
pprint.pprint(np.linalg.multi_dot([P, L, U]))

A:
array([[2, 3, 2],
       [1, 3, 2],
       [3, 4, 1]])
P:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [0.66666667, 0.2       , 1.        ]])
U:
array([[3.        , 4.        , 1.        ],
       [0.        , 1.66666667, 1.66666667],
       [0.        , 0.        , 1.        ]])
PLU :
array([[2., 3., 2.],
       [1., 3., 2.],
       [3., 4., 1.]])


In [17]:
pprint.pprint(np.linalg.multi_dot([L, U]))

array([[3., 4., 1.],
       [1., 3., 2.],
       [2., 3., 2.]])


## LU Decomposition โดยใช้ Doolittle Algorithm

โค้ดจาก https://www.geeksforgeeks.org/doolittle-algorithm-lu-decomposition/

In [18]:
MAX = 100
  
def luDecomposition(mat, n): 
    """ Python3 Program to decompose a matrix into lower and upper traingular matrix """
  
    lower = [[0 for x in range(n)]  
                for y in range(n)]
    upper = [[0 for x in range(n)]  
                for y in range(n)]
                  
    # Decomposing matrix into Upper  
    # and Lower triangular matrix 
    for k in range(n): 
  
        # Upper Triangular 
        for m in range(k, n):  
  
            # Summation of L(k, j) * U(j, m) 
            s = 0; 
            for j in range(k): 
                s += (lower[k][j] * upper[j][m]); 
  
            # Evaluating U(k, m) 
            upper[k][m] = mat[k][m] - s; 
  
        # Lower Triangular 
        for i in range(k, n): 
            if (i == k): 
                lower[i][i] = 1; # Diagonal as 1 
            else: 
  
                # Summation of L(i, j) * U(j, k) 
                s = 0; 
                for j in range(k): 
                    s += (lower[i][j] * upper[j][k]); 
  
                # Evaluating L(i, k) 
                lower[i][k] = float((mat[i][k] - s) /
                                       upper[k][k]);
  
    # setw is for displaying nicely 
    print("Lower Triangular\t\tUpper Triangular"); 
  
    # Displaying the result : 
    for i in range(n): 
          
        # Lower 
        for j in range(n): 
            print(f'{lower[i][j]:.3f}', end = "\t");  
        print("", end = "\t"); 
  
        # Upper 
        for j in range(n): 
            print(f'{upper[i][j]:.3f}', end = "\t"); 
        print(""); 
# This code is contributed by mits 

In [19]:
mat = [[2, 3, 2], 
       [1, 3, 2], 
       [3, 4, 1]]
  
luDecomposition(mat, 3); 

Lower Triangular		Upper Triangular
1.000	0.000	0.000		2.000	3.000	2.000	
0.500	1.000	0.000		0.000	1.500	1.000	
1.500	-0.333	1.000		0.000	0.000	-1.667	


In [20]:
mat = [[3, 3, 4], 
       [6, 8, 7], 
       [-3, 5, -9]]
luDecomposition(mat, 3)

Lower Triangular		Upper Triangular
1.000	0.000	0.000		3.000	3.000	4.000	
2.000	1.000	0.000		0.000	2.000	-1.000	
-1.000	4.000	1.000		0.000	0.000	-1.000	
