# Orthogonal

Two vectors are called **orthogonal** if $u \cdot v = 0$

In [1]:
import numpy as np

# orthogonal
u1 = [3,1,1]
u2 = [-1,2,1]
u3 = [-1/2,-2,7/2]
print('u1 . u2 = ', np.dot(u1,u2))
print('u1 . u3 = ', np.dot(u1,u3))
print('u2 . u3 = ', np.dot(u2,u3))

u1 . u2 =  0
u1 . u3 =  0.0
u2 . u3 =  0.0


## Orthogonal projection

In [2]:
# orthogonal project
y = np.array([7, 6])
u = np.array([4, 2])
y_hat = (y@u) / (u@u) * u
print('y = ', y)
print('u = ', u)
print('y_hat = ', y_hat) # find projection of y on u
z = y - y_hat
print('z = ', z)
print('y_hat . z = ', np.dot(y_hat, z))

y =  [7 6]
u =  [4 2]
y_hat =  [8. 4.]
z =  [-1.  2.]
y_hat . z =  0.0


, where $y \cdot u = 7*4 + 6*2 = 40$

In [3]:
y@u

40

and $u \cdot u = 4*4 + 2*2 = 20$

In [4]:
u@u

20

## QR factorization

ใช้ฟังก์ชัน `numpy.linalg.qr` (https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html)

In [5]:
# QR factorization
import numpy.linalg as LA
# A = np.array([[1, 2, 5], [-1, 1, -4], [-1, 4, -3], [1, -4, 7], [1, 2, 1]])
A = np.array([[2,1], [2,0], [1,1]])
q, r = LA.qr(A)
print('A = \n', A)
print('q = \n', q)
print('r = \n', r)
print('A = QR? ', np.allclose(A, np.dot(q, r)))  # a does equal qr
print('R = QT A? ', np.allclose(r, q.T @ A))  # a does equal qr
print('QTQ = \n', np.round(q.T @ q, 10))

A = 
 [[2 1]
 [2 0]
 [1 1]]
q = 
 [[-0.66666667  0.33333333]
 [-0.66666667 -0.66666667]
 [-0.33333333  0.66666667]]
r = 
 [[-3. -1.]
 [ 0.  1.]]
A = QR?  True
R = QT A?  True
QTQ = 
 [[ 1. -0.]
 [-0.  1.]]


In [6]:
print('QT Q = \n', q.T @ q)

QT Q = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


## QR algorithm using eigenvalues and eigenvectors

From spectral theorem, where $A_{k+1} = Q^{-1}_k A_k Q_k$, so

$A_{k+1} = R_k Q_k$

and from QR decomposition

$A_k = Q_k R_k$

As the iteration goes, we will eventually converge to an upper triangular matrix form, where eigenvalues are the diagonal entries.

In [7]:
# QR algorithm
# eigenvalues and eigenvectors
A = np.array([[1, 6], 
              [5, 2]])
print('A = \n', A)
Ak = A
Q = np.eye(2)
for i in range(20):
    q, r = LA.qr(Ak)
    Ak = r @ q
    print('\n\t i = %d' % i)
    print('eigenvalues = \n', Ak)

print('Ak = \n', np.round(Ak, 6))
print('eigenvalues = ', np.diag(Ak))

w, v = LA.eig(A)
print('eigenvalues from eig = ', w)

A = 
 [[1 6]
 [5 2]]

	 i = 0
eigenvalues = 
 [[ 4.07692308  4.38461538]
 [ 5.38461538 -1.07692308]]

	 i = 1
eigenvalues = 
 [[ 5.50252951  4.30522766]
 [ 3.30522766 -2.50252951]]

	 i = 2
eigenvalues = 
 [[ 6.73936889  1.24614251]
 [ 2.24614251 -3.73936889]]

	 i = 3
eigenvalues = 
 [[ 6.73932699  2.24626823]
 [ 1.24626823 -3.73932699]]

	 i = 4
eigenvalues = 
 [[ 7.01733607 -0.25709521]
 [ 0.74290479 -4.01733607]]

	 i = 5
eigenvalues = 
 [[ 6.94589323  1.41774014]
 [ 0.41774014 -3.94589323]]

	 i = 6
eigenvalues = 
 [[ 7.01663059 -0.75843167]
 [ 0.24156833 -4.01663059]]

	 i = 7
eigenvalues = 
 [[ 6.98579503  1.13722282]
 [ 0.13722282 -3.98579503]]

	 i = 8
eigenvalues = 
 [[ 7.00658768 -0.92129811]
 [ 0.07870189 -4.00658768]]

	 i = 9
eigenvalues = 
 [[ 6.99573501  1.04488232]
 [ 0.04488232 -3.99573501]]

	 i = 10
eigenvalues = 
 [[ 7.00227389 -0.97432274]
 [ 0.02567726 -4.00227389]]

	 i = 11
eigenvalues = 
 [[ 6.99864729  1.014663  ]
 [ 0.014663   -3.99864729]]

	 i = 12
eigenva