# Matrix Factorization

In [1]:
#%% 1
import numpy as np
a = np.array([[0, 1, 2], 
              [1, 0, 3], 
              [4, -3, 8]])
b = np.eye(a.shape[0])
print(a.shape)
print(a)
print(np.diag(a))
print(b)

(3, 3)
[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
[0 0 8]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
a.shape[0]

3

In [3]:
a = np.array([[0, 1, 2], 
              [1, 0, 3], 
              [4, -3, 8]])
print(a)

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]


In [14]:
c = np.array([[1],[2],[3]])

In [15]:
c.shape

(3, 1)

In [18]:
c

array([[1],
       [2],
       [3]])

In [20]:
c.ndim

2

In [16]:
d = np.array([1,2,3])

In [17]:
d.shape

(3,)

In [21]:
d.ndim

1

In [22]:
np.diag(d)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [23]:
np.diag(c)

array([1])

In [19]:
d

array([1, 2, 3])

In [4]:
a.shape

(3, 3)

In [6]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## LU Decomposition

In [24]:
#%% 2
import pprint
import scipy.linalg

A = np.array([[2, 3, 2], 
              [1, 3, 2], 
              [3, 4, 1]])
P, L, U = scipy.linalg.lu(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

print("PLU :")
pprint.pprint(np.linalg.multi_dot([P, L, U]))

A:
array([[2, 3, 2],
       [1, 3, 2],
       [3, 4, 1]])
P:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [0.66666667, 0.2       , 1.        ]])
U:
array([[3.        , 4.        , 1.        ],
       [0.        , 1.66666667, 1.66666667],
       [0.        , 0.        , 1.        ]])
PLU :
array([[2., 3., 2.],
       [1., 3., 2.],
       [3., 4., 1.]])


In [25]:
pprint.pprint(np.linalg.multi_dot([L, U]))

array([[3., 4., 1.],
       [1., 3., 2.],
       [2., 3., 2.]])


## LU Decomposition โดยใช้ Doolittle Algorithm

In [28]:
# Python3 Program to decompose  
# a matrix into lower and 
# upper traingular matrix 
MAX = 100; 
  
def luDecomposition(mat, n): 
  
    lower = [[0 for x in range(n)]  
                for y in range(n)]; 
    upper = [[0 for x in range(n)]  
                for y in range(n)]; 
                  
    # Decomposing matrix into Upper  
    # and Lower triangular matrix 
    for k in range(n): 
  
        # Upper Triangular 
        for m in range(k, n):  
  
            # Summation of L(k, j) * U(j, m) 
            s = 0; 
            for j in range(k): 
                s += (lower[k][j] * upper[j][m]); 
  
            # Evaluating U(k, m) 
            upper[k][m] = mat[k][m] - s; 
  
        # Lower Triangular 
        for i in range(k, n): 
            if (i == k): 
                lower[i][i] = 1; # Diagonal as 1 
            else: 
  
                # Summation of L(i, j) * U(j, k) 
                s = 0; 
                for j in range(k): 
                    s += (lower[i][j] * upper[j][k]); 
  
                # Evaluating L(i, k) 
                lower[i][k] = float((mat[i][k] - s) /
                                       upper[k][k]);
  
    # setw is for displaying nicely 
    print("Lower Triangular\t\tUpper Triangular"); 
  
    # Displaying the result : 
    for i in range(n): 
          
        # Lower 
        for j in range(n): 
            print(f'{lower[i][j]:.3f}', end = "\t");  
        print("", end = "\t"); 
  
        # Upper 
        for j in range(n): 
            print(f'{upper[i][j]:.3f}', end = "\t"); 
        print(""); 
  
# Driver code 
mat = [[2, 3, 2], 
       [1, 3, 2], 
       [3, 4, 1]]
  
luDecomposition(mat, 3); 
  
# This code is contributed by mits 

Lower Triangular		Upper Triangular
1.000	0.000	0.000		2.000	3.000	2.000	
0.500	1.000	0.000		0.000	1.500	1.000	
1.500	-0.333	1.000		0.000	0.000	-1.667	
