# Matrix Algebra

* การบวก Matrix ใน Python
* การคูณ Matrix ใน Python
* การหา Inverse ใน Python โดยใช้ Gauss-Jordan Method


## การบวก Matrix ใน Python

โดยไม่ใช้ `NumPy`

In [1]:
A = [[4, 2, 5], 
     [-1, 3, 2]]
B = [[1, 1, 1],
     [3, 5, 7]]
print(A+B)


[[4, 2, 5], [-1, 3, 2], [1, 1, 1], [3, 5, 7]]


ไม่สามารถใช้เครื่องหมาย `+` กันตรง ๆ ได้ เนื่องจาก `list` มองเครื่องหมายบวกเป็นการรวมสมาชิกของทั้งสองลิสเข้าด้วยกัน

In [2]:
C = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
for c in C:
    print(c)

[5, 3, 6]
[2, 8, 9]


โดยใช้ `NumPy`

In [3]:
import numpy as np
a = np.array(A)
b = np.array(B)
print(a+b)

[[5 3 6]
 [2 8 9]]


`NumPy array` มีคุณสมบัติในการ [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) จึงสามารถใช้เครื่องหมายบวกได้เลย

In [4]:
print('A = \n', a)

A = 
 [[ 4  2  5]
 [-1  3  2]]


In [5]:
b = np.array([1, 2, 3])
print('B = \n', b)

B = 
 [1 2 3]


In [6]:
print('A + B = \n', a+b)

A + B = 
 [[5 4 8]
 [0 5 5]]


## การคูณ Matrix ใน Python

โดยใช้ฟังก์ชัน [np.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) ของ `NumPy`

In [7]:
A = [[-1, 0], 
     [2, 3]]
B = [[1, 2],
     [3, 0]]
a = np.array(A)
b = np.array(B)
print('AB = \n', np.matmul(a, b))
print('BA = \n', np.matmul(b, a))

AB = 
 [[-1 -2]
 [11  4]]
BA = 
 [[ 3  6]
 [-3  0]]


Matrix Multiplication ไม่การันตีคุณสมบัติการสลับที่

In [8]:
A = [[1, 2], 
    [2, 3]]
B = [[2, 4],
    [4, 6]]
a = np.array(A)
b = np.array(B)
print('AB = \n', np.matmul(a, b))
print('BA = \n', np.matmul(b, a))

AB = 
 [[10 16]
 [16 26]]
BA = 
 [[10 16]
 [16 26]]


## การหา Inverse ใน Python โดยใช้หลักการเดียวกันกับ Gauss-Jordan Method

ใน Gauss-Jordan Method เรา augment แมทริกซ์ด้วย identity matrix เพื่อหา solution ที่ทำให้ระบบสมการเป็นจริง ซึ่งในที่นี้ solution ก็คือ inverse (จากนิยาม $AA^{-1} = I$) ในโค้ดนี้ผมจึงใช้คำสั่ง [`np.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) ในการแก้ระบบสมการ และผลลัพธ์ที่ได้จึงเป็น inverse

In [9]:
#%% 3
import numpy as np
a = np.array([[0, 1, 2], 
              [1, 0, 3], 
              [4, -3, 8]])
b = np.eye(a.shape[0])
print('A = \n', a)
ainv = np.linalg.solve(a, b)
print('A-1 = \n', ainv)
print('A-1 A = \n', np.matmul(ainv, a))
print('A A-1 = \n', np.matmul(a, ainv))

A = 
 [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
A-1 = 
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
A-1 A = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A A-1 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ค่า determinant ของแมทริกซ์จะต้อง**ไม่ใช่ศูนย์** จึงจะหา inverse ได้

In [10]:
np.linalg.det(a)

-2.0

`Python` อาจมีปัญหาเรื่อง `underflow` ได้ เช่น

In [11]:
0.1+0.2

0.30000000000000004